# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabPycnometer = QtWidgets.QTabWidget(self.centralwidget)
        self.tabPycnometer.setEnabled(True)
        self.tabPycnometer.setGeometry(QtCore.QRect(0, 0, 1280, 680))
        self.tabPycnometer.setMinimumSize(QtCore.QSize(1280, 680))
        self.tabPycnometer.setMaximumSize(QtCore.QSize(1280, 680))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tabPycnometer.setFont(font)
        self.tabPycnometer.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabPycnometer.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabPycnometer.setElideMode(QtCore.Qt.ElideNone)
        self.tabPycnometer.setUsesScrollButtons(True)
        self.tabPycnometer.setDocumentMode(False)
        self.tabPycnometer.setMovable(False)
        self.tabPycnometer.setObjectName("tabPycnometer")
        self.t1 = QtWidgets.QWidget()
        self.t1.setObjectName("t1")
        self.t1_groupGeneralInformation = QtWidgets.QGroupBox(self.t1)
        self.t1_groupGeneralInformation.setGeometry(QtCore.QRect(760, 10, 500, 180))
        self.t1_groupGeneralInformation.setMinimumSize(QtCore.QSize(500, 180))
        self.t1_groupGeneralInformation.setMaximumSize(QtCore.QSize(500, 180))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_groupGeneralInformation.setFont(font)
        self.t1_groupGeneralInformation.setObjectName("t1_groupGeneralInformation")
        self.t1_gMI_Edit1 = QtWidgets.QLineEdit(self.t1_groupGeneralInformation)
        self.t1_gMI_Edit1.setGeometry(QtCore.QRect(170, 20, 310, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gMI_Edit1.setFont(font)
        self.t1_gMI_Edit1.setObjectName("t1_gMI_Edit1")
        self.t1_gMI_Edit2 = QtWidgets.QLineEdit(self.t1_groupGeneralInformation)
        self.t1_gMI_Edit2.setGeometry(QtCore.QRect(170, 60, 310, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gMI_Edit2.setFont(font)
        self.t1_gMI_Edit2.setObjectName("t1_gMI_Edit2")
        self.t1_gMI_Edit3 = QtWidgets.QLineEdit(self.t1_groupGeneralInformation)
        self.t1_gMI_Edit3.setGeometry(QtCore.QRect(170, 100, 310, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gMI_Edit3.setFont(font)
        self.t1_gMI_Edit3.setObjectName("t1_gMI_Edit3")
        self.t1_gMI_Edit4 = QtWidgets.QLineEdit(self.t1_groupGeneralInformation)
        self.t1_gMI_Edit4.setGeometry(QtCore.QRect(170, 140, 310, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gMI_Edit4.setFont(font)
        self.t1_gMI_Edit4.setObjectName("t1_gMI_Edit4")
        self.t1_gMI_lbl1 = QtWidgets.QLabel(self.t1_groupGeneralInformation)
        self.t1_gMI_lbl1.setGeometry(QtCore.QRect(10, 20, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gMI_lbl1.setFont(font)
        self.t1_gMI_lbl1.setObjectName("t1_gMI_lbl1")
        self.t1_gMI_lbl2 = QtWidgets.QLabel(self.t1_groupGeneralInformation)
        self.t1_gMI_lbl2.setGeometry(QtCore.QRect(10, 60, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gMI_lbl2.setFont(font)
        self.t1_gMI_lbl2.setObjectName("t1_gMI_lbl2")
        self.t1_gMI_lbl3 = QtWidgets.QLabel(self.t1_groupGeneralInformation)
        self.t1_gMI_lbl3.setGeometry(QtCore.QRect(10, 100, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gMI_lbl3.setFont(font)
        self.t1_gMI_lbl3.setObjectName("t1_gMI_lbl3")
        self.t1_gMI_lbl4 = QtWidgets.QLabel(self.t1_groupGeneralInformation)
        self.t1_gMI_lbl4.setGeometry(QtCore.QRect(10, 140, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gMI_lbl4.setFont(font)
        self.t1_gMI_lbl4.setObjectName("t1_gMI_lbl4")
        self.t1_groupSamplePreparation = QtWidgets.QGroupBox(self.t1)
        self.t1_groupSamplePreparation.setGeometry(QtCore.QRect(760, 200, 500, 160))
        self.t1_groupSamplePreparation.setMinimumSize(QtCore.QSize(500, 160))
        self.t1_groupSamplePreparation.setMaximumSize(QtCore.QSize(500, 160))
        self.t1_groupSamplePreparation.setObjectName("t1_groupSamplePreparation")
        self.t1_gSP_groupRB = QtWidgets.QGroupBox(self.t1_groupSamplePreparation)
        self.t1_gSP_groupRB.setGeometry(QtCore.QRect(20, 30, 250, 110))
        self.t1_gSP_groupRB.setMinimumSize(QtCore.QSize(250, 110))
        self.t1_gSP_groupRB.setMaximumSize(QtCore.QSize(250, 110))
        self.t1_gSP_groupRB.setTitle("")
        self.t1_gSP_groupRB.setObjectName("t1_gSP_groupRB")
        self.t1_gSP_gRB_rb1 = QtWidgets.QRadioButton(self.t1_gSP_groupRB)
        self.t1_gSP_gRB_rb1.setGeometry(QtCore.QRect(10, 10, 210, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1_gSP_gRB_rb1.sizePolicy().hasHeightForWidth())
        self.t1_gSP_gRB_rb1.setSizePolicy(sizePolicy)
        self.t1_gSP_gRB_rb1.setChecked(True)
        self.t1_gSP_gRB_rb1.setObjectName("t1_gSP_gRB_rb1")
        self.t1_gSP_gRB_rb2 = QtWidgets.QRadioButton(self.t1_gSP_groupRB)
        self.t1_gSP_gRB_rb2.setGeometry(QtCore.QRect(10, 45, 210, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1_gSP_gRB_rb2.sizePolicy().hasHeightForWidth())
        self.t1_gSP_gRB_rb2.setSizePolicy(sizePolicy)
        self.t1_gSP_gRB_rb2.setChecked(False)
        self.t1_gSP_gRB_rb2.setObjectName("t1_gSP_gRB_rb2")
        self.t1_gSP_gRB_rb3 = QtWidgets.QRadioButton(self.t1_gSP_groupRB)
        self.t1_gSP_gRB_rb3.setGeometry(QtCore.QRect(10, 80, 210, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1_gSP_gRB_rb3.sizePolicy().hasHeightForWidth())
        self.t1_gSP_gRB_rb3.setSizePolicy(sizePolicy)
        self.t1_gSP_gRB_rb3.setObjectName("t1_gSP_gRB_rb3")
        self.t1_gSP_Edit1 = QtWidgets.QLineEdit(self.t1_groupSamplePreparation)
        self.t1_gSP_Edit1.setGeometry(QtCore.QRect(300, 90, 170, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gSP_Edit1.setFont(font)
        self.t1_gSP_Edit1.setAlignment(QtCore.Qt.AlignCenter)
        self.t1_gSP_Edit1.setObjectName("t1_gSP_Edit1")
        self.t1_gSP_lbl1 = QtWidgets.QLabel(self.t1_groupSamplePreparation)
        self.t1_gSP_lbl1.setGeometry(QtCore.QRect(300, 45, 170, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gSP_lbl1.setFont(font)
        self.t1_gSP_lbl1.setAlignment(QtCore.Qt.AlignCenter)
        self.t1_gSP_lbl1.setObjectName("t1_gSP_lbl1")
        self.t1_groupMeasurement = QtWidgets.QGroupBox(self.t1)
        self.t1_groupMeasurement.setGeometry(QtCore.QRect(760, 370, 500, 270))
        self.t1_groupMeasurement.setMinimumSize(QtCore.QSize(500, 270))
        self.t1_groupMeasurement.setMaximumSize(QtCore.QSize(500, 270))
        self.t1_groupMeasurement.setObjectName("t1_groupMeasurement")
        self.t1_gM_Edit1 = QtWidgets.QLineEdit(self.t1_groupMeasurement)
        self.t1_gM_Edit1.setGeometry(QtCore.QRect(220, 30, 260, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gM_Edit1.setFont(font)
        self.t1_gM_Edit1.setAlignment(QtCore.Qt.AlignCenter)
        self.t1_gM_Edit1.setObjectName("t1_gM_Edit1")
        self.t1_gM_lbl1 = QtWidgets.QLabel(self.t1_groupMeasurement)
        self.t1_gM_lbl1.setGeometry(QtCore.QRect(40, 30, 170, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gM_lbl1.setFont(font)
        self.t1_gM_lbl1.setObjectName("t1_gM_lbl1")
        self.t1_gM_lbl2 = QtWidgets.QLabel(self.t1_groupMeasurement)
        self.t1_gM_lbl2.setGeometry(QtCore.QRect(40, 60, 170, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gM_lbl2.setFont(font)
        self.t1_gM_lbl2.setObjectName("t1_gM_lbl2")
        self.t1_gM_lbl3 = QtWidgets.QLabel(self.t1_groupMeasurement)
        self.t1_gM_lbl3.setGeometry(QtCore.QRect(40, 90, 170, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gM_lbl3.setFont(font)
        self.t1_gM_lbl3.setObjectName("t1_gM_lbl3")
        self.t1_gM_lbl4 = QtWidgets.QLabel(self.t1_groupMeasurement)
        self.t1_gM_lbl4.setGeometry(QtCore.QRect(40, 120, 170, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gM_lbl4.setFont(font)
        self.t1_gM_lbl4.setObjectName("t1_gM_lbl4")
        self.t1_gM_Edit2 = QtWidgets.QLineEdit(self.t1_groupMeasurement)
        self.t1_gM_Edit2.setGeometry(QtCore.QRect(220, 90, 260, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gM_Edit2.setFont(font)
        self.t1_gM_Edit2.setAlignment(QtCore.Qt.AlignCenter)
        self.t1_gM_Edit2.setObjectName("t1_gM_Edit2")
        self.t1_gM_Edit3 = QtWidgets.QLineEdit(self.t1_groupMeasurement)
        self.t1_gM_Edit3.setGeometry(QtCore.QRect(220, 120, 260, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gM_Edit3.setFont(font)
        self.t1_gM_Edit3.setAlignment(QtCore.Qt.AlignCenter)
        self.t1_gM_Edit3.setObjectName("t1_gM_Edit3")
        self.t1_gM_cmd1 = QtWidgets.QComboBox(self.t1_groupMeasurement)
        self.t1_gM_cmd1.setGeometry(QtCore.QRect(220, 60, 260, 25))
        self.t1_gM_cmd1.setObjectName("t1_gM_cmd1")
        self.t1_gM_button1 = QtWidgets.QPushButton(self.t1_groupMeasurement)
        self.t1_gM_button1.setEnabled(False)
        self.t1_gM_button1.setGeometry(QtCore.QRect(30, 210, 200, 32))
        self.t1_gM_button1.setObjectName("t1_gM_button1")
        self.t1_gM_button2 = QtWidgets.QPushButton(self.t1_groupMeasurement)
        self.t1_gM_button2.setGeometry(QtCore.QRect(270, 160, 200, 32))
        self.t1_gM_button2.setObjectName("t1_gM_button2")
        self.t1_gM_button3 = QtWidgets.QPushButton(self.t1_groupMeasurement)
        self.t1_gM_button3.setGeometry(QtCore.QRect(30, 160, 200, 32))
        self.t1_gM_button3.setObjectName("t1_gM_button3")
        self.t1_gM_button4 = QtWidgets.QPushButton(self.t1_groupMeasurement)
        self.t1_gM_button4.setEnabled(False)
        self.t1_gM_button4.setGeometry(QtCore.QRect(270, 210, 200, 32))
        self.t1_gM_button4.setObjectName("t1_gM_button4")
        self.t1_groupMeasurementResults = QtWidgets.QGroupBox(self.t1)
        self.t1_groupMeasurementResults.setGeometry(QtCore.QRect(10, 530, 730, 110))
        self.t1_groupMeasurementResults.setMinimumSize(QtCore.QSize(730, 110))
        self.t1_groupMeasurementResults.setMaximumSize(QtCore.QSize(730, 110))
        self.t1_groupMeasurementResults.setObjectName("t1_groupMeasurementResults")
        self.t1_gMR_Edit2 = QtWidgets.QLineEdit(self.t1_groupMeasurementResults)
        self.t1_gMR_Edit2.setGeometry(QtCore.QRect(160, 60, 180, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gMR_Edit2.setFont(font)
        self.t1_gMR_Edit2.setAlignment(QtCore.Qt.AlignCenter)
        self.t1_gMR_Edit2.setReadOnly(True)
        self.t1_gMR_Edit2.setObjectName("t1_gMR_Edit2")
        self.t1_gMR_Edit1 = QtWidgets.QLineEdit(self.t1_groupMeasurementResults)
        self.t1_gMR_Edit1.setGeometry(QtCore.QRect(160, 30, 180, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gMR_Edit1.setFont(font)
        self.t1_gMR_Edit1.setAlignment(QtCore.Qt.AlignCenter)
        self.t1_gMR_Edit1.setReadOnly(True)
        self.t1_gMR_Edit1.setObjectName("t1_gMR_Edit1")
        self.t1_gMR_lbl2 = QtWidgets.QLabel(self.t1_groupMeasurementResults)
        self.t1_gMR_lbl2.setGeometry(QtCore.QRect(10, 60, 140, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gMR_lbl2.setFont(font)
        self.t1_gMR_lbl2.setObjectName("t1_gMR_lbl2")
        self.t1_gMR_lbl1 = QtWidgets.QLabel(self.t1_groupMeasurementResults)
        self.t1_gMR_lbl1.setGeometry(QtCore.QRect(10, 30, 140, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gMR_lbl1.setFont(font)
        self.t1_gMR_lbl1.setObjectName("t1_gMR_lbl1")
        self.t1_gMR_lbl4 = QtWidgets.QLabel(self.t1_groupMeasurementResults)
        self.t1_gMR_lbl4.setGeometry(QtCore.QRect(390, 60, 140, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gMR_lbl4.setFont(font)
        self.t1_gMR_lbl4.setObjectName("t1_gMR_lbl4")
        self.t1_gMR_Edit3 = QtWidgets.QLineEdit(self.t1_groupMeasurementResults)
        self.t1_gMR_Edit3.setGeometry(QtCore.QRect(540, 30, 180, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gMR_Edit3.setFont(font)
        self.t1_gMR_Edit3.setAlignment(QtCore.Qt.AlignCenter)
        self.t1_gMR_Edit3.setReadOnly(True)
        self.t1_gMR_Edit3.setObjectName("t1_gMR_Edit3")
        self.t1_gMR_Edit4 = QtWidgets.QLineEdit(self.t1_groupMeasurementResults)
        self.t1_gMR_Edit4.setGeometry(QtCore.QRect(540, 60, 180, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gMR_Edit4.setFont(font)
        self.t1_gMR_Edit4.setAlignment(QtCore.Qt.AlignCenter)
        self.t1_gMR_Edit4.setReadOnly(True)
        self.t1_gMR_Edit4.setObjectName("t1_gMR_Edit4")
        self.t1_gMR_lbl3 = QtWidgets.QLabel(self.t1_groupMeasurementResults)
        self.t1_gMR_lbl3.setGeometry(QtCore.QRect(390, 30, 140, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t1_gMR_lbl3.setFont(font)
        self.t1_gMR_lbl3.setObjectName("t1_gMR_lbl3")
        self.tabPycnometer.addTab(self.t1, "")
        self.t2 = QtWidgets.QWidget()
        self.t2.setObjectName("t2")
        self.t2_groupCalibratonResult = QtWidgets.QGroupBox(self.t2)
        self.t2_groupCalibratonResult.setGeometry(QtCore.QRect(10, 530, 730, 110))
        self.t2_groupCalibratonResult.setMinimumSize(QtCore.QSize(730, 110))
        self.t2_groupCalibratonResult.setMaximumSize(QtCore.QSize(730, 110))
        self.t2_groupCalibratonResult.setObjectName("t2_groupCalibratonResult")
        self.t2_gCR_Edit2 = QtWidgets.QLineEdit(self.t2_groupCalibratonResult)
        self.t2_gCR_Edit2.setGeometry(QtCore.QRect(250, 80, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t2_gCR_Edit2.setFont(font)
        self.t2_gCR_Edit2.setAlignment(QtCore.Qt.AlignCenter)
        self.t2_gCR_Edit2.setReadOnly(True)
        self.t2_gCR_Edit2.setObjectName("t2_gCR_Edit2")
        self.t2_gCR_Edit1 = QtWidgets.QLineEdit(self.t2_groupCalibratonResult)
        self.t2_gCR_Edit1.setGeometry(QtCore.QRect(250, 50, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t2_gCR_Edit1.setFont(font)
        self.t2_gCR_Edit1.setAlignment(QtCore.Qt.AlignCenter)
        self.t2_gCR_Edit1.setReadOnly(True)
        self.t2_gCR_Edit1.setObjectName("t2_gCR_Edit1")
        self.t2_gCR_lbl2 = QtWidgets.QLabel(self.t2_groupCalibratonResult)
        self.t2_gCR_lbl2.setGeometry(QtCore.QRect(10, 80, 230, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t2_gCR_lbl2.setFont(font)
        self.t2_gCR_lbl2.setObjectName("t2_gCR_lbl2")
        self.t2_gCR_lbl1 = QtWidgets.QLabel(self.t2_groupCalibratonResult)
        self.t2_gCR_lbl1.setGeometry(QtCore.QRect(10, 50, 230, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t2_gCR_lbl1.setFont(font)
        self.t2_gCR_lbl1.setObjectName("t2_gCR_lbl1")
        self.t2_gCR_lbl3 = QtWidgets.QLabel(self.t2_groupCalibratonResult)
        self.t2_gCR_lbl3.setGeometry(QtCore.QRect(519, 30, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t2_gCR_lbl3.setFont(font)
        self.t2_gCR_lbl3.setAlignment(QtCore.Qt.AlignCenter)
        self.t2_gCR_lbl3.setObjectName("t2_gCR_lbl3")
        self.t2_gCR_button1 = QtWidgets.QPushButton(self.t2_groupCalibratonResult)
        self.t2_gCR_button1.setEnabled(False)
        self.t2_gCR_button1.setGeometry(QtCore.QRect(520, 70, 201, 31))
        self.t2_gCR_button1.setObjectName("t2_gCR_button1")
        self.t2_gCR_Edit4 = QtWidgets.QLineEdit(self.t2_groupCalibratonResult)
        self.t2_gCR_Edit4.setGeometry(QtCore.QRect(390, 80, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t2_gCR_Edit4.setFont(font)
        self.t2_gCR_Edit4.setAlignment(QtCore.Qt.AlignCenter)
        self.t2_gCR_Edit4.setReadOnly(True)
        self.t2_gCR_Edit4.setObjectName("t2_gCR_Edit4")
        self.t2_gCR_Edit3 = QtWidgets.QLineEdit(self.t2_groupCalibratonResult)
        self.t2_gCR_Edit3.setGeometry(QtCore.QRect(390, 50, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t2_gCR_Edit3.setFont(font)
        self.t2_gCR_Edit3.setAlignment(QtCore.Qt.AlignCenter)
        self.t2_gCR_Edit3.setReadOnly(True)
        self.t2_gCR_Edit3.setObjectName("t2_gCR_Edit3")
        self.t2_gCR_lbl4 = QtWidgets.QLabel(self.t2_groupCalibratonResult)
        self.t2_gCR_lbl4.setGeometry(QtCore.QRect(250, 20, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t2_gCR_lbl4.setFont(font)
        self.t2_gCR_lbl4.setAlignment(QtCore.Qt.AlignCenter)
        self.t2_gCR_lbl4.setObjectName("t2_gCR_lbl4")
        self.t2_gCR_lbl5 = QtWidgets.QLabel(self.t2_groupCalibratonResult)
        self.t2_gCR_lbl5.setGeometry(QtCore.QRect(390, 20, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t2_gCR_lbl5.setFont(font)
        self.t2_gCR_lbl5.setAlignment(QtCore.Qt.AlignCenter)
        self.t2_gCR_lbl5.setObjectName("t2_gCR_lbl5")
        self.t2_groupInitialData = QtWidgets.QGroupBox(self.t2)
        self.t2_groupInitialData.setGeometry(QtCore.QRect(760, 10, 500, 260))
        self.t2_groupInitialData.setMinimumSize(QtCore.QSize(500, 260))
        self.t2_groupInitialData.setMaximumSize(QtCore.QSize(500, 260))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t2_groupInitialData.setFont(font)
        self.t2_groupInitialData.setObjectName("t2_groupInitialData")
        self.t2_gID_Edit1 = QtWidgets.QLineEdit(self.t2_groupInitialData)
        self.t2_gID_Edit1.setGeometry(QtCore.QRect(320, 80, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t2_gID_Edit1.setFont(font)
        self.t2_gID_Edit1.setAlignment(QtCore.Qt.AlignCenter)
        self.t2_gID_Edit1.setObjectName("t2_gID_Edit1")
        self.t2_gID_Edit2 = QtWidgets.QLineEdit(self.t2_groupInitialData)
        self.t2_gID_Edit2.setGeometry(QtCore.QRect(320, 125, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t2_gID_Edit2.setFont(font)
        self.t2_gID_Edit2.setAlignment(QtCore.Qt.AlignCenter)
        self.t2_gID_Edit2.setObjectName("t2_gID_Edit2")
        self.t2_gID_lbl2 = QtWidgets.QLabel(self.t2_groupInitialData)
        self.t2_gID_lbl2.setGeometry(QtCore.QRect(31, 80, 280, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t2_gID_lbl2.setFont(font)
        self.t2_gID_lbl2.setObjectName("t2_gID_lbl2")
        self.t2_gID_lbl3 = QtWidgets.QLabel(self.t2_groupInitialData)
        self.t2_gID_lbl3.setGeometry(QtCore.QRect(31, 125, 280, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t2_gID_lbl3.setFont(font)
        self.t2_gID_lbl3.setObjectName("t2_gID_lbl3")
        self.t2_gID_button1 = QtWidgets.QPushButton(self.t2_groupInitialData)
        self.t2_gID_button1.setEnabled(False)
        self.t2_gID_button1.setGeometry(QtCore.QRect(30, 220, 200, 32))
        self.t2_gID_button1.setObjectName("t2_gID_button1")
        self.t2_gID_button2 = QtWidgets.QPushButton(self.t2_groupInitialData)
        self.t2_gID_button2.setGeometry(QtCore.QRect(270, 175, 200, 32))
        self.t2_gID_button2.setObjectName("t2_gID_button2")
        self.t2_gID_lbl1 = QtWidgets.QLabel(self.t2_groupInitialData)
        self.t2_gID_lbl1.setGeometry(QtCore.QRect(31, 30, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t2_gID_lbl1.setFont(font)
        self.t2_gID_lbl1.setObjectName("t2_gID_lbl1")
        self.t2_gID_cmd1 = QtWidgets.QComboBox(self.t2_groupInitialData)
        self.t2_gID_cmd1.setGeometry(QtCore.QRect(221, 30, 240, 31))
        self.t2_gID_cmd1.setObjectName("t2_gID_cmd1")
        self.t2_gID_button3 = QtWidgets.QPushButton(self.t2_groupInitialData)
        self.t2_gID_button3.setGeometry(QtCore.QRect(30, 175, 200, 32))
        self.t2_gID_button3.setObjectName("t2_gID_button3")
        self.t2_gID_button4 = QtWidgets.QPushButton(self.t2_groupInitialData)
        self.t2_gID_button4.setEnabled(False)
        self.t2_gID_button4.setGeometry(QtCore.QRect(270, 220, 200, 32))
        self.t2_gID_button4.setObjectName("t2_gID_button4")
        self.tabPycnometer.addTab(self.t2, "")
        self.t3 = QtWidgets.QWidget()
        self.t3.setObjectName("t3")
        self.t3_checkValve1 = QtWidgets.QCheckBox(self.t3)
        self.t3_checkValve1.setEnabled(True)
        self.t3_checkValve1.setGeometry(QtCore.QRect(296, 298, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.t3_checkValve1.setFont(font)
        self.t3_checkValve1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t3_checkValve1.setText("")
        self.t3_checkValve1.setIconSize(QtCore.QSize(16, 16))
        self.t3_checkValve1.setChecked(False)
        self.t3_checkValve1.setAutoRepeatDelay(300)
        self.t3_checkValve1.setObjectName("t3_checkValve1")
        self.t3_checkValve5 = QtWidgets.QCheckBox(self.t3)
        self.t3_checkValve5.setEnabled(True)
        self.t3_checkValve5.setGeometry(QtCore.QRect(296, 458, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.t3_checkValve5.setFont(font)
        self.t3_checkValve5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t3_checkValve5.setText("")
        self.t3_checkValve5.setObjectName("t3_checkValve5")
        self.t3_checkValve4 = QtWidgets.QCheckBox(self.t3)
        self.t3_checkValve4.setEnabled(True)
        self.t3_checkValve4.setGeometry(QtCore.QRect(803, 298, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.t3_checkValve4.setFont(font)
        self.t3_checkValve4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t3_checkValve4.setText("")
        self.t3_checkValve4.setObjectName("t3_checkValve4")
        self.t3_checkValve3 = QtWidgets.QCheckBox(self.t3)
        self.t3_checkValve3.setEnabled(True)
        self.t3_checkValve3.setGeometry(QtCore.QRect(631, 298, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.t3_checkValve3.setFont(font)
        self.t3_checkValve3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t3_checkValve3.setText("")
        self.t3_checkValve3.setObjectName("t3_checkValve3")
        self.t3_checkValve2 = QtWidgets.QCheckBox(self.t3)
        self.t3_checkValve2.setEnabled(True)
        self.t3_checkValve2.setGeometry(QtCore.QRect(468, 298, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.t3_checkValve2.setFont(font)
        self.t3_checkValve2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t3_checkValve2.setText("")
        self.t3_checkValve2.setObjectName("t3_checkValve2")
        self.t3_lblPycnometerScheme = QtWidgets.QLabel(self.t3)
        self.t3_lblPycnometerScheme.setGeometry(QtCore.QRect(113, 115, 1041, 421))
        self.t3_lblPycnometerScheme.setText("")
        self.t3_lblPycnometerScheme.setPixmap(QtGui.QPixmap("attachment/Pycnometer scheme.jpg"))
        self.t3_lblPycnometerScheme.setScaledContents(True)
        self.t3_lblPycnometerScheme.setObjectName("t3_lblPycnometerScheme")
        self.t3_lblFon = QtWidgets.QLabel(self.t3)
        self.t3_lblFon.setGeometry(QtCore.QRect(-57, -55, 1471, 771))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.t3_lblFon.setPalette(palette)
        self.t3_lblFon.setAutoFillBackground(True)
        self.t3_lblFon.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.t3_lblFon.setFrameShadow(QtWidgets.QFrame.Plain)
        self.t3_lblFon.setText("")
        self.t3_lblFon.setObjectName("t3_lblFon")
        self.t3_lblValve1 = QtWidgets.QLabel(self.t3)
        self.t3_lblValve1.setGeometry(QtCore.QRect(293, 280, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.t3_lblValve1.setFont(font)
        self.t3_lblValve1.setAlignment(QtCore.Qt.AlignCenter)
        self.t3_lblValve1.setObjectName("t3_lblValve1")
        self.t3_lblValve2 = QtWidgets.QLabel(self.t3)
        self.t3_lblValve2.setGeometry(QtCore.QRect(465, 280, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.t3_lblValve2.setFont(font)
        self.t3_lblValve2.setAlignment(QtCore.Qt.AlignCenter)
        self.t3_lblValve2.setObjectName("t3_lblValve2")
        self.t3_lblValve3 = QtWidgets.QLabel(self.t3)
        self.t3_lblValve3.setGeometry(QtCore.QRect(628, 280, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.t3_lblValve3.setFont(font)
        self.t3_lblValve3.setAlignment(QtCore.Qt.AlignCenter)
        self.t3_lblValve3.setObjectName("t3_lblValve3")
        self.t3_lblValve4 = QtWidgets.QLabel(self.t3)
        self.t3_lblValve4.setGeometry(QtCore.QRect(800, 280, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.t3_lblValve4.setFont(font)
        self.t3_lblValve4.setAlignment(QtCore.Qt.AlignCenter)
        self.t3_lblValve4.setObjectName("t3_lblValve4")
        self.t3_lblValve5 = QtWidgets.QLabel(self.t3)
        self.t3_lblValve5.setGeometry(QtCore.QRect(293, 440, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.t3_lblValve5.setFont(font)
        self.t3_lblValve5.setAlignment(QtCore.Qt.AlignCenter)
        self.t3_lblValve5.setObjectName("t3_lblValve5")
        self.t3_lblPressure1 = QtWidgets.QLabel(self.t3)
        self.t3_lblPressure1.setGeometry(QtCore.QRect(503, 105, 180, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.t3_lblPressure1.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.t3_lblPressure1.setFont(font)
        self.t3_lblPressure1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.t3_lblPressure1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.t3_lblPressure1.setLineWidth(3)
        self.t3_lblPressure1.setMidLineWidth(0)
        self.t3_lblPressure1.setAlignment(QtCore.Qt.AlignCenter)
        self.t3_lblPressure1.setObjectName("t3_lblPressure1")
        self.t3_lblPressure2 = QtWidgets.QLabel(self.t3)
        self.t3_lblPressure2.setGeometry(QtCore.QRect(503, 145, 180, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.t3_lblPressure2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.t3_lblPressure2.setFont(font)
        self.t3_lblPressure2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.t3_lblPressure2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.t3_lblPressure2.setLineWidth(3)
        self.t3_lblPressure2.setMidLineWidth(0)
        self.t3_lblPressure2.setAlignment(QtCore.Qt.AlignCenter)
        self.t3_lblPressure2.setObjectName("t3_lblPressure2")
        self.t3_lbl_Helium = QtWidgets.QLabel(self.t3)
        self.t3_lbl_Helium.setGeometry(QtCore.QRect(113, 155, 261, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.t3_lbl_Helium.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.t3_lbl_Helium.setFont(font)
        self.t3_lbl_Helium.setAutoFillBackground(True)
        self.t3_lbl_Helium.setAlignment(QtCore.Qt.AlignCenter)
        self.t3_lbl_Helium.setObjectName("t3_lbl_Helium")
        self.t3_lbl_Atmosphere = QtWidgets.QLabel(self.t3)
        self.t3_lbl_Atmosphere.setGeometry(QtCore.QRect(883, 275, 261, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.t3_lbl_Atmosphere.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.t3_lbl_Atmosphere.setFont(font)
        self.t3_lbl_Atmosphere.setAutoFillBackground(True)
        self.t3_lbl_Atmosphere.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.t3_lbl_Atmosphere.setObjectName("t3_lbl_Atmosphere")
        self.t3_lbl_Vacuum = QtWidgets.QLabel(self.t3)
        self.t3_lbl_Vacuum.setGeometry(QtCore.QRect(-12, 435, 261, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.t3_lbl_Vacuum.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.t3_lbl_Vacuum.setFont(font)
        self.t3_lbl_Vacuum.setAutoFillBackground(True)
        self.t3_lbl_Vacuum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t3_lbl_Vacuum.setObjectName("t3_lbl_Vacuum")
        self.no_small = QtWidgets.QLabel(self.t3)
        self.no_small.setGeometry(QtCore.QRect(450, 270, 111, 81))
        self.no_small.setText("")
        self.no_small.setTextFormat(QtCore.Qt.PlainText)
        self.no_small.setPixmap(QtGui.QPixmap("attachment/no small.png"))
        self.no_small.setScaledContents(False)
        self.no_small.setObjectName("no_small")
        self.t3_lblFon.raise_()
        self.t3_lblPycnometerScheme.raise_()
        self.t3_checkValve1.raise_()
        self.t3_checkValve5.raise_()
        self.t3_checkValve4.raise_()
        self.t3_checkValve3.raise_()
        self.t3_checkValve2.raise_()
        self.t3_lblValve1.raise_()
        self.t3_lblValve2.raise_()
        self.t3_lblValve3.raise_()
        self.t3_lblValve4.raise_()
        self.t3_lblValve5.raise_()
        self.t3_lblPressure1.raise_()
        self.t3_lblPressure2.raise_()
        self.t3_lbl_Helium.raise_()
        self.t3_lbl_Atmosphere.raise_()
        self.t3_lbl_Vacuum.raise_()
        self.no_small.raise_()
        self.tabPycnometer.addTab(self.t3, "")
        self.t4 = QtWidgets.QWidget()
        self.t4.setObjectName("t4")
        self.t4_groupInterfaceSettings = QtWidgets.QGroupBox(self.t4)
        self.t4_groupInterfaceSettings.setGeometry(QtCore.QRect(20, 50, 380, 210))
        self.t4_groupInterfaceSettings.setObjectName("t4_groupInterfaceSettings")
        self.t4_gIS_lbl1 = QtWidgets.QLabel(self.t4_groupInterfaceSettings)
        self.t4_gIS_lbl1.setGeometry(QtCore.QRect(10, 40, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t4_gIS_lbl1.setFont(font)
        self.t4_gIS_lbl1.setObjectName("t4_gIS_lbl1")
        self.t4_gIS_cmd1 = QtWidgets.QComboBox(self.t4_groupInterfaceSettings)
        self.t4_gIS_cmd1.setGeometry(QtCore.QRect(160, 40, 211, 25))
        self.t4_gIS_cmd1.setObjectName("t4_gIS_cmd1")
        self.t4_gIS_flag = QtWidgets.QLabel(self.t4_groupInterfaceSettings)
        self.t4_gIS_flag.setGeometry(QtCore.QRect(120, 90, 151, 91))
        self.t4_gIS_flag.setFrameShape(QtWidgets.QFrame.Box)
        self.t4_gIS_flag.setText("")
        self.t4_gIS_flag.setPixmap(QtGui.QPixmap("attachment/Russian.png"))
        self.t4_gIS_flag.setScaledContents(True)
        self.t4_gIS_flag.setWordWrap(False)
        self.t4_gIS_flag.setObjectName("t4_gIS_flag")
        self.t4_button_2 = QtWidgets.QPushButton(self.t4)
        self.t4_button_2.setGeometry(QtCore.QRect(1050, 600, 180, 31))
        self.t4_button_2.setObjectName("t4_button_2")
        self.t4_groupMeasurementSettings = QtWidgets.QGroupBox(self.t4)
        self.t4_groupMeasurementSettings.setGeometry(QtCore.QRect(20, 310, 380, 210))
        self.t4_groupMeasurementSettings.setObjectName("t4_groupMeasurementSettings")
        self.t4_gMS_lbl1 = QtWidgets.QLabel(self.t4_groupMeasurementSettings)
        self.t4_gMS_lbl1.setGeometry(QtCore.QRect(10, 30, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t4_gMS_lbl1.setFont(font)
        self.t4_gMS_lbl1.setObjectName("t4_gMS_lbl1")
        self.t4_gMS_cmd1 = QtWidgets.QComboBox(self.t4_groupMeasurementSettings)
        self.t4_gMS_cmd1.setGeometry(QtCore.QRect(160, 30, 211, 25))
        self.t4_gMS_cmd1.setObjectName("t4_gMS_cmd1")
        self.t4_gMS_lbl2 = QtWidgets.QLabel(self.t4_groupMeasurementSettings)
        self.t4_gMS_lbl2.setGeometry(QtCore.QRect(10, 80, 271, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t4_gMS_lbl2.setFont(font)
        self.t4_gMS_lbl2.setObjectName("t4_gMS_lbl2")
        self.t4_gMS_cmd2 = QtWidgets.QComboBox(self.t4_groupMeasurementSettings)
        self.t4_gMS_cmd2.setGeometry(QtCore.QRect(260, 80, 111, 25))
        self.t4_gMS_cmd2.setObjectName("t4_gMS_cmd2")
        self.t4_gMS_lbl3 = QtWidgets.QLabel(self.t4_groupMeasurementSettings)
        self.t4_gMS_lbl3.setGeometry(QtCore.QRect(10, 130, 231, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t4_gMS_lbl3.setFont(font)
        self.t4_gMS_lbl3.setObjectName("t4_gMS_lbl3")
        self.t4_MS_Edit1 = QtWidgets.QLineEdit(self.t4_groupMeasurementSettings)
        self.t4_MS_Edit1.setGeometry(QtCore.QRect(260, 130, 113, 20))
        self.t4_MS_Edit1.setAlignment(QtCore.Qt.AlignCenter)
        self.t4_MS_Edit1.setObjectName("t4_MS_Edit1")
        self.t4_MS_Edit2 = QtWidgets.QLineEdit(self.t4_groupMeasurementSettings)
        self.t4_MS_Edit2.setGeometry(QtCore.QRect(260, 170, 113, 20))
        self.t4_MS_Edit2.setAlignment(QtCore.Qt.AlignCenter)
        self.t4_MS_Edit2.setObjectName("t4_MS_Edit2")
        self.t4_gMS_lbl4 = QtWidgets.QLabel(self.t4_groupMeasurementSettings)
        self.t4_gMS_lbl4.setGeometry(QtCore.QRect(10, 170, 231, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t4_gMS_lbl4.setFont(font)
        self.t4_gMS_lbl4.setObjectName("t4_gMS_lbl4")
        self.t4_button_1 = QtWidgets.QPushButton(self.t4)
        self.t4_button_1.setGeometry(QtCore.QRect(850, 600, 180, 31))
        self.t4_button_1.setObjectName("t4_button_1")
        self.t4_groupManualControl = QtWidgets.QGroupBox(self.t4)
        self.t4_groupManualControl.setGeometry(QtCore.QRect(435, 50, 380, 210))
        self.t4_groupManualControl.setObjectName("t4_groupManualControl")
        self.t4_gMC_Edit1 = QtWidgets.QLineEdit(self.t4_groupManualControl)
        self.t4_gMC_Edit1.setGeometry(QtCore.QRect(260, 30, 113, 20))
        self.t4_gMC_Edit1.setAlignment(QtCore.Qt.AlignCenter)
        self.t4_gMC_Edit1.setObjectName("t4_gMC_Edit1")
        self.t4_gMC_lbl1 = QtWidgets.QLabel(self.t4_groupManualControl)
        self.t4_gMC_lbl1.setGeometry(QtCore.QRect(10, 30, 231, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t4_gMC_lbl1.setFont(font)
        self.t4_gMC_lbl1.setObjectName("t4_gMC_lbl1")
        self.t4_gMC_chb1 = QtWidgets.QCheckBox(self.t4_groupManualControl)
        self.t4_gMC_chb1.setGeometry(QtCore.QRect(10, 60, 361, 31))
        self.t4_gMC_chb1.setObjectName("t4_gMC_chb1")
        self.t4_groupReportSetup = QtWidgets.QGroupBox(self.t4)
        self.t4_groupReportSetup.setGeometry(QtCore.QRect(435, 310, 380, 210))
        self.t4_groupReportSetup.setObjectName("t4_groupReportSetup")
        self.t4_gRS_Edit1 = QtWidgets.QLineEdit(self.t4_groupReportSetup)
        self.t4_gRS_Edit1.setGeometry(QtCore.QRect(10, 100, 301, 20))
        self.t4_gRS_Edit1.setAlignment(QtCore.Qt.AlignCenter)
        self.t4_gRS_Edit1.setReadOnly(True)
        self.t4_gRS_Edit1.setObjectName("t4_gRS_Edit1")
        self.t4_gRS_lbl1 = QtWidgets.QLabel(self.t4_groupReportSetup)
        self.t4_gRS_lbl1.setGeometry(QtCore.QRect(10, 70, 361, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t4_gRS_lbl1.setFont(font)
        self.t4_gRS_lbl1.setObjectName("t4_gRS_lbl1")
        self.t4_gRS_chb1 = QtWidgets.QCheckBox(self.t4_groupReportSetup)
        self.t4_gRS_chb1.setGeometry(QtCore.QRect(10, 30, 361, 31))
        self.t4_gRS_chb1.setObjectName("t4_gRS_chb1")
        self.t4_gRS_lbl2 = QtWidgets.QLabel(self.t4_groupReportSetup)
        self.t4_gRS_lbl2.setGeometry(QtCore.QRect(10, 140, 361, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t4_gRS_lbl2.setFont(font)
        self.t4_gRS_lbl2.setObjectName("t4_gRS_lbl2")
        self.t4_gRS_Edit2 = QtWidgets.QLineEdit(self.t4_groupReportSetup)
        self.t4_gRS_Edit2.setGeometry(QtCore.QRect(10, 170, 301, 20))
        self.t4_gRS_Edit2.setAlignment(QtCore.Qt.AlignCenter)
        self.t4_gRS_Edit2.setReadOnly(True)
        self.t4_gRS_Edit2.setObjectName("t4_gRS_Edit2")
        self.t4_gRS_button1 = QtWidgets.QPushButton(self.t4_groupReportSetup)
        self.t4_gRS_button1.setGeometry(QtCore.QRect(320, 98, 24, 24))
        self.t4_gRS_button1.setObjectName("t4_gRS_button1")
        self.t4_gRS_button3 = QtWidgets.QPushButton(self.t4_groupReportSetup)
        self.t4_gRS_button3.setGeometry(QtCore.QRect(320, 168, 24, 24))
        self.t4_gRS_button3.setObjectName("t4_gRS_button3")
        self.t4_gRS_button2 = QtWidgets.QPushButton(self.t4_groupReportSetup)
        self.t4_gRS_button2.setGeometry(QtCore.QRect(350, 98, 24, 24))
        self.t4_gRS_button2.setObjectName("t4_gRS_button2")
        self.t4_gRS_button4 = QtWidgets.QPushButton(self.t4_groupReportSetup)
        self.t4_gRS_button4.setGeometry(QtCore.QRect(350, 168, 24, 24))
        self.t4_gRS_button4.setObjectName("t4_gRS_button4")
        self.t4_groupSavingResult = QtWidgets.QGroupBox(self.t4)
        self.t4_groupSavingResult.setGeometry(QtCore.QRect(850, 50, 380, 471))
        self.t4_groupSavingResult.setObjectName("t4_groupSavingResult")
        self.t4_gSR_Edit1 = QtWidgets.QLineEdit(self.t4_groupSavingResult)
        self.t4_gSR_Edit1.setGeometry(QtCore.QRect(10, 110, 361, 20))
        self.t4_gSR_Edit1.setAlignment(QtCore.Qt.AlignCenter)
        self.t4_gSR_Edit1.setObjectName("t4_gSR_Edit1")
        self.t4_gSR_chb2 = QtWidgets.QCheckBox(self.t4_groupSavingResult)
        self.t4_gSR_chb2.setGeometry(QtCore.QRect(10, 70, 361, 31))
        self.t4_gSR_chb2.setObjectName("t4_gSR_chb2")
        self.t4_gSR_lbl1 = QtWidgets.QLabel(self.t4_groupSavingResult)
        self.t4_gSR_lbl1.setGeometry(QtCore.QRect(10, 300, 361, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t4_gSR_lbl1.setFont(font)
        self.t4_gSR_lbl1.setAlignment(QtCore.Qt.AlignCenter)
        self.t4_gSR_lbl1.setObjectName("t4_gSR_lbl1")
        self.t4_gSR_chb1 = QtWidgets.QCheckBox(self.t4_groupSavingResult)
        self.t4_gSR_chb1.setGeometry(QtCore.QRect(10, 30, 361, 31))
        self.t4_gSR_chb1.setObjectName("t4_gSR_chb1")
        self.t4_gSR_Edit2 = QtWidgets.QLineEdit(self.t4_groupSavingResult)
        self.t4_gSR_Edit2.setGeometry(QtCore.QRect(142, 350, 231, 20))
        self.t4_gSR_Edit2.setAlignment(QtCore.Qt.AlignCenter)
        self.t4_gSR_Edit2.setObjectName("t4_gSR_Edit2")
        self.t4_gSR_lbl2 = QtWidgets.QLabel(self.t4_groupSavingResult)
        self.t4_gSR_lbl2.setGeometry(QtCore.QRect(10, 350, 121, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t4_gSR_lbl2.setFont(font)
        self.t4_gSR_lbl2.setObjectName("t4_gSR_lbl2")
        self.t4_gSR_Edit3 = QtWidgets.QLineEdit(self.t4_groupSavingResult)
        self.t4_gSR_Edit3.setGeometry(QtCore.QRect(142, 390, 231, 20))
        self.t4_gSR_Edit3.setAlignment(QtCore.Qt.AlignCenter)
        self.t4_gSR_Edit3.setObjectName("t4_gSR_Edit3")
        self.t4_gSR_lbl3 = QtWidgets.QLabel(self.t4_groupSavingResult)
        self.t4_gSR_lbl3.setGeometry(QtCore.QRect(10, 390, 121, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.t4_gSR_lbl3.setFont(font)
        self.t4_gSR_lbl3.setTextFormat(QtCore.Qt.AutoText)
        self.t4_gSR_lbl3.setObjectName("t4_gSR_lbl3")
        self.t4_gSR_button1 = QtWidgets.QPushButton(self.t4_groupSavingResult)
        self.t4_gSR_button1.setGeometry(QtCore.QRect(10, 430, 171, 31))
        self.t4_gSR_button1.setObjectName("t4_gSR_button1")
        self.t4_gSR_button2 = QtWidgets.QPushButton(self.t4_groupSavingResult)
        self.t4_gSR_button2.setGeometry(QtCore.QRect(200, 430, 171, 31))
        self.t4_gSR_button2.setObjectName("t4_gSR_button2")
        self.t4_gSR_lbl4 = QtWidgets.QLabel(self.t4_groupSavingResult)
        self.t4_gSR_lbl4.setGeometry(QtCore.QRect(10, 250, 361, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.t4_gSR_lbl4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.t4_gSR_lbl4.setFont(font)
        self.t4_gSR_lbl4.setAlignment(QtCore.Qt.AlignCenter)
        self.t4_gSR_lbl4.setObjectName("t4_gSR_lbl4")
        self.t4_gSR_wifi = QtWidgets.QLabel(self.t4_groupSavingResult)
        self.t4_gSR_wifi.setGeometry(QtCore.QRect(140, 140, 101, 91))
        self.t4_gSR_wifi.setText("")
        self.t4_gSR_wifi.setPixmap(QtGui.QPixmap("attachment/wifi.png"))
        self.t4_gSR_wifi.setScaledContents(True)
        self.t4_gSR_wifi.setObjectName("t4_gSR_wifi")
        self.tabPycnometer.addTab(self.t4, "")
        self.t5 = QtWidgets.QWidget()
        self.t5.setObjectName("t5")
        self.tabPycnometer.addTab(self.t5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menumenu1 = QtWidgets.QMenu(self.menubar)
        self.menumenu1.setObjectName("menumenu1")
        self.menumenu2 = QtWidgets.QMenu(self.menubar)
        self.menumenu2.setObjectName("menumenu2")
        self.menumenu3 = QtWidgets.QMenu(self.menubar)
        self.menumenu3.setObjectName("menumenu3")
        self.menumenu4 = QtWidgets.QMenu(self.menubar)
        self.menumenu4.setObjectName("menumenu4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionmenu1_command1 = QtWidgets.QAction(MainWindow)
        self.actionmenu1_command1.setObjectName("actionmenu1_command1")
        self.actionmenu4_command1 = QtWidgets.QAction(MainWindow)
        self.actionmenu4_command1.setEnabled(False)
        self.actionmenu4_command1.setObjectName("actionmenu4_command1")
        self.menumenu1.addAction(self.actionmenu1_command1)
        self.menumenu4.addAction(self.actionmenu4_command1)
        self.menubar.addAction(self.menumenu1.menuAction())
        self.menubar.addAction(self.menumenu2.menuAction())
        self.menubar.addAction(self.menumenu3.menuAction())
        self.menubar.addAction(self.menumenu4.menuAction())

        self.retranslateUi(MainWindow)
        self.tabPycnometer.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.t1_groupGeneralInformation.setTitle(_translate("MainWindow", "t1_groupGeneralInformation"))
        self.t1_gMI_Edit1.setText(_translate("MainWindow", "t1_gMI_Edit1"))
        self.t1_gMI_Edit2.setText(_translate("MainWindow", "t1_gMI_Edit2"))
        self.t1_gMI_Edit3.setText(_translate("MainWindow", "t1_gMI_Edit3"))
        self.t1_gMI_Edit4.setText(_translate("MainWindow", "t1_gMI_Edit4"))
        self.t1_gMI_lbl1.setText(_translate("MainWindow", "t1_gMI_lbl1"))
        self.t1_gMI_lbl2.setText(_translate("MainWindow", "t1_gMI_lbl2"))
        self.t1_gMI_lbl3.setText(_translate("MainWindow", "t1_gMI_lbl3"))
        self.t1_gMI_lbl4.setText(_translate("MainWindow", "t1_gMI_lbl4"))
        self.t1_groupSamplePreparation.setTitle(_translate("MainWindow", "t1_groupSamplePreparation"))
        self.t1_gSP_gRB_rb1.setText(_translate("MainWindow", "t1_gSP_gRB_rb1"))
        self.t1_gSP_gRB_rb2.setText(_translate("MainWindow", "t1_gSP_gRB_rb2"))
        self.t1_gSP_gRB_rb3.setText(_translate("MainWindow", "t1_gSP_gRB_rb3"))
        self.t1_gSP_Edit1.setText(_translate("MainWindow", "t1_gSP_Edit1"))
        self.t1_gSP_lbl1.setText(_translate("MainWindow", "t1_gSP_lbl1"))
        self.t1_groupMeasurement.setTitle(_translate("MainWindow", "t1_groupMeasurement"))
        self.t1_gM_Edit1.setText(_translate("MainWindow", "t1_gM_Edit1"))
        self.t1_gM_lbl1.setText(_translate("MainWindow", "t1_gM_lbl1"))
        self.t1_gM_lbl2.setText(_translate("MainWindow", "t1_gM_lbl2"))
        self.t1_gM_lbl3.setText(_translate("MainWindow", "t1_gM_lbl3"))
        self.t1_gM_lbl4.setText(_translate("MainWindow", "t1_gM_lbl4"))
        self.t1_gM_Edit2.setText(_translate("MainWindow", "t1_gM_Edit2"))
        self.t1_gM_Edit3.setText(_translate("MainWindow", "t1_gM_Edit3"))
        self.t1_gM_button1.setText(_translate("MainWindow", "t1_gM_button1"))
        self.t1_gM_button2.setText(_translate("MainWindow", "t1_gM_button2"))
        self.t1_gM_button3.setText(_translate("MainWindow", "t1_gM_button3"))
        self.t1_gM_button4.setText(_translate("MainWindow", "t1_gM_button4"))
        self.t1_groupMeasurementResults.setTitle(_translate("MainWindow", "t1_groupMeasurementResults"))
        self.t1_gMR_Edit2.setText(_translate("MainWindow", "t1_gMR_Edit2"))
        self.t1_gMR_Edit1.setText(_translate("MainWindow", "t1_gMR_Edit1"))
        self.t1_gMR_lbl2.setText(_translate("MainWindow", "t1_gMR_lbl2"))
        self.t1_gMR_lbl1.setText(_translate("MainWindow", "t1_gMR_lbl1"))
        self.t1_gMR_lbl4.setText(_translate("MainWindow", "t1_gMR_lbl4"))
        self.t1_gMR_Edit3.setText(_translate("MainWindow", "t1_gMR_Edit3"))
        self.t1_gMR_Edit4.setText(_translate("MainWindow", "t1_gMR_Edit4"))
        self.t1_gMR_lbl3.setText(_translate("MainWindow", "t1_gMR_lbl3"))
        self.tabPycnometer.setTabText(self.tabPycnometer.indexOf(self.t1), _translate("MainWindow", "t1"))
        self.t2_groupCalibratonResult.setTitle(_translate("MainWindow", "t2_groupCalibratonResult"))
        self.t2_gCR_Edit2.setText(_translate("MainWindow", "t2_gCR_Edit2"))
        self.t2_gCR_Edit1.setText(_translate("MainWindow", "t2_gCR_Edit1"))
        self.t2_gCR_lbl2.setText(_translate("MainWindow", "t2_gCR_lbl2"))
        self.t2_gCR_lbl1.setText(_translate("MainWindow", "t2_gCR_lbl1"))
        self.t2_gCR_lbl3.setText(_translate("MainWindow", "t2_gCR_lbl3"))
        self.t2_gCR_button1.setText(_translate("MainWindow", "t2_gCR_button1"))
        self.t2_gCR_Edit4.setText(_translate("MainWindow", "t2_gCR_Edit4"))
        self.t2_gCR_Edit3.setText(_translate("MainWindow", "t2_gCR_Edit3"))
        self.t2_gCR_lbl4.setText(_translate("MainWindow", "t2_gCR_lbl4"))
        self.t2_gCR_lbl5.setText(_translate("MainWindow", "t2_gCR_lbl5"))
        self.t2_groupInitialData.setTitle(_translate("MainWindow", "t2_groupInitialData"))
        self.t2_gID_Edit1.setText(_translate("MainWindow", "t2_gID_Edit1"))
        self.t2_gID_Edit2.setText(_translate("MainWindow", "t2_gID_Edit2"))
        self.t2_gID_lbl2.setText(_translate("MainWindow", "t2_gID_lbl2"))
        self.t2_gID_lbl3.setText(_translate("MainWindow", "t2_gID_lbl3"))
        self.t2_gID_button1.setText(_translate("MainWindow", "t2_gID_button1"))
        self.t2_gID_button2.setText(_translate("MainWindow", "t2_gID_button2"))
        self.t2_gID_lbl1.setText(_translate("MainWindow", "t2_gID_lbl1"))
        self.t2_gID_button3.setText(_translate("MainWindow", "t2_gID_button3"))
        self.t2_gID_button4.setText(_translate("MainWindow", "t2_gID_button4"))
        self.tabPycnometer.setTabText(self.tabPycnometer.indexOf(self.t2), _translate("MainWindow", "t2"))
        self.t3_lblValve1.setText(_translate("MainWindow", "K1"))
        self.t3_lblValve2.setText(_translate("MainWindow", "K2"))
        self.t3_lblValve3.setText(_translate("MainWindow", "K3"))
        self.t3_lblValve4.setText(_translate("MainWindow", "K4"))
        self.t3_lblValve5.setText(_translate("MainWindow", "K5"))
        self.t3_lblPressure1.setText(_translate("MainWindow", "t3_lblPressure1"))
        self.t3_lblPressure2.setText(_translate("MainWindow", "0,00"))
        self.t3_lbl_Helium.setText(_translate("MainWindow", "t3_lbl_Helium"))
        self.t3_lbl_Atmosphere.setText(_translate("MainWindow", "t3_lbl_Atmosphere"))
        self.t3_lbl_Vacuum.setText(_translate("MainWindow", "t3_lbl_Vacuum"))
        self.tabPycnometer.setTabText(self.tabPycnometer.indexOf(self.t3), _translate("MainWindow", "t3"))
        self.t4_groupInterfaceSettings.setTitle(_translate("MainWindow", "t4_groupInterfaceSettings"))
        self.t4_gIS_lbl1.setText(_translate("MainWindow", "t4_gIS_lbl1"))
        self.t4_button_2.setText(_translate("MainWindow", "t4_button_2"))
        self.t4_groupMeasurementSettings.setTitle(_translate("MainWindow", "t4_groupMeasurementSettings"))
        self.t4_gMS_lbl1.setText(_translate("MainWindow", "t4_gMS_lbl1"))
        self.t4_gMS_lbl2.setText(_translate("MainWindow", "t4_gMS_lbl2"))
        self.t4_gMS_lbl3.setText(_translate("MainWindow", "t4_gMS_lbl3"))
        self.t4_MS_Edit1.setText(_translate("MainWindow", "t4_MS_Edit1"))
        self.t4_MS_Edit2.setText(_translate("MainWindow", "t4_MS_Edit2"))
        self.t4_gMS_lbl4.setText(_translate("MainWindow", "t4_gMS_lbl4"))
        self.t4_button_1.setText(_translate("MainWindow", "t4_button_1"))
        self.t4_groupManualControl.setTitle(_translate("MainWindow", "t4_groupManualСontrol"))
        self.t4_gMC_Edit1.setText(_translate("MainWindow", "t4_gMC_Edit1"))
        self.t4_gMC_lbl1.setText(_translate("MainWindow", "t4_gMC_lbl1"))
        self.t4_gMC_chb1.setText(_translate("MainWindow", "t4_gMC_chb1"))
        self.t4_groupReportSetup.setTitle(_translate("MainWindow", "t4_groupReportSetup"))
        self.t4_gRS_Edit1.setText(_translate("MainWindow", "t4_gRS_Edit1"))
        self.t4_gRS_lbl1.setText(_translate("MainWindow", "t4_gRS_lbl1"))
        self.t4_gRS_chb1.setText(_translate("MainWindow", "t4_gRS_chb1"))
        self.t4_gRS_lbl2.setText(_translate("MainWindow", "t4_gRS_lbl2"))
        self.t4_gRS_Edit2.setText(_translate("MainWindow", "t4_gRS_Edit2"))
        self.t4_gRS_button1.setText(_translate("MainWindow", "+"))
        self.t4_gRS_button3.setText(_translate("MainWindow", "+"))
        self.t4_gRS_button2.setText(_translate("MainWindow", "-"))
        self.t4_gRS_button4.setText(_translate("MainWindow", "-"))
        self.t4_groupSavingResult.setTitle(_translate("MainWindow", "t4_groupSavingResult"))
        self.t4_gSR_Edit1.setText(_translate("MainWindow", "t4_gSR_Edit1"))
        self.t4_gSR_chb2.setText(_translate("MainWindow", "t4_gSR_chb2"))
        self.t4_gSR_lbl1.setText(_translate("MainWindow", "t4_gSR_lbl1"))
        self.t4_gSR_chb1.setText(_translate("MainWindow", "t4_gSR_chb1"))
        self.t4_gSR_Edit2.setText(_translate("MainWindow", "t4_gSR_Edit2"))
        self.t4_gSR_lbl2.setText(_translate("MainWindow", "t4_gSR_lbl2"))
        self.t4_gSR_Edit3.setText(_translate("MainWindow", "t4_gSR_Edit3"))
        self.t4_gSR_lbl3.setText(_translate("MainWindow", "t4_gSR_lbl3"))
        self.t4_gSR_button1.setText(_translate("MainWindow", "t4_gSR_button1"))
        self.t4_gSR_button2.setText(_translate("MainWindow", "t4_gSR_button2"))
        self.t4_gSR_lbl4.setText(_translate("MainWindow", "t4_gSR_lbl4"))
        self.tabPycnometer.setTabText(self.tabPycnometer.indexOf(self.t4), _translate("MainWindow", "t4"))
        self.tabPycnometer.setTabText(self.tabPycnometer.indexOf(self.t5), _translate("MainWindow", "t5"))
        self.menumenu1.setTitle(_translate("MainWindow", "menu1"))
        self.menumenu2.setTitle(_translate("MainWindow", "menu2"))
        self.menumenu3.setTitle(_translate("MainWindow", "menu3"))
        self.menumenu4.setTitle(_translate("MainWindow", "menu4"))
        self.actionmenu1_command1.setText(_translate("MainWindow", "menu1_command1"))
        self.actionmenu4_command1.setText(_translate("MainWindow", "actionmenu4_command1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

